### ISSUE TITLE
Master List

### ISSUE THREAD

**Issue by joshgosselin** [thepottingshed/octobercms-default-theme#9]
Core Plugins
---

**AddThis Plugin**

`ThePottingShed.AddThis`

* [x] Create below issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-addthis-plugin/issues/4 )
* [x] Add migration to seed AddThis Settings model with TPS Base Theme website account

---

**Backend Plugin**

* [x] Add User relationship

**Contact Details Plugin**

* [x] Add migration to seed Social Media Profiles with faker data
* [x] Add migration to seed Location List with faker data
* [x] Add migration to seed Opening Hours

---

**Campaign Monitor Plugin**

`ThePottingShed.CampaignMonitor`

* [x] Create below issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-campaign-monitor-plugin/issues/4 )
* [x] Content Blocks
    * [x] Create Newsletter Sign Up Form
* [x] Add migration to seed Campaign Monitor Settings model with TPS Base Theme client account

---

**Outdated Browser Plugin**

`ThePottingShed.OutdatedBrowser`

* [x] Create below issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-outdated-browser-plugin/issues/7 )
* [x] Add IE 10 and IE 11 to browser list
* [x] Update component to reference logo and colours from `ThePottingShed.Theme` plugin
* [x] Set IE 10 as default browser
* [x] Display IE 11 as banner at top of screen

---

**SEO Plugins**

`ThePottingShed.Amp`
`ThePottingShed.Meta`
`ThePottingShed.OpenGraph`
`ThePottingShed.Schema`
`ThePottingShed.Seo`
`ThePottingShed.TwitterCard`

* [x] Remove AMP CSS field

---

**Theme  Plugin**

`ThePottingShed.Theme`

* [x] Create below issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-theme-plugin/issues/16 )
* [x] Add field for SVG logo
* [x] Add field forJPG logo
* [x] Add border radius for button ( so not effected by global border radius )
* [ ] Review Global Font Variable Names
* [x] Move `burgerMenu` effect from component to ThemeData
* [x] Add Favicon fields and allow upload of Realfavicon ZIP file
* [ ] Contact form etc ( @davethepottingshed can you elaborate on this please )
* [x] Seed Backup Manager table

---

**Ui Kit Plugin**

`ThePottingShed.UiKit`

* [x] Add migration to seed default settings

Frontend Plugins
---

* Blog
* Careers
* Carousel
* Contact
* Content Blocks
* Portfolio
* Services
* Team
* Testimonials

---

**Blog Plugin**

* https://github.com/thepottingshed/octobercms-blog-plugin

`ThePottingShed.Blog`

* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-blog-plugin/issues/16 )
* [x] List current model fields in preparation for meeting
* [x] LESS from GTA
* [x] Content Blocks
    * [x] Create News Article List Content Block
* [x] Confirm default fields for Blog Post model
* [x] Confirm default fields for Blog Category model
* [x] Add migration to seed Blog Category model faker data
* [x] Add migration to seed Blog Post model faker data
* [ ] Replace migration seed faker images with those provided by Silvie for the other plugins
* [x] Add migration to seed `RainLab.Sitemap`
* [x] Add migration to seed user permissions

**Fields**

`RainLab\Blog\Models\Category`

* `name`
* `slug`
* `description`

`RainLab\Blog\Models\Post`

* `title`
* `slug`
* `categories`
* `published`
* `published_at`
* `excerpt`
* `featured_images`
* `created_at`
* `updated_at`
* `user_id`

---

**Careers Plugin**

* https://github.com/thepottingshed/octobercms-careers-plugin

`ThePottingShed.Careers`

* [x] Add Plugin Repo to Milestones
* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-careers-plugin/issues/1 )
* [x] Add default Labels with Jules script
* [x] List current model fields in preparation for meeting
* [x] LESS from PF+A / GTA
* [x] Confirm default fields for Job Vacancy model
* [x] Add migration to seed Job Vacancy model faker data
* [x] Add migration to seed `RainLab.Sitemap`
* [x] Add migration to seed user permissions

**Fields**

`ThePottingShed\Careers\Models\Job`

* `title`
* `slug`
* `overview`
* `skills`
* `duties`
* `is_public`
* `created_at`
* `updated_at`

**Thoughts**

How would a client share a link to a specific job?

---

**Carousel Plugin**

* https://github.com/thepottingshed/octobercms-carousel-plugin

`ThePottingShed.Carousel`

* [x] Create Plugin Repo
* [x] Add Plugin Repo to Milestones
* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-carousel-plugin/issues/1 )
* [x] Add default Labels with Jules script
* [x] List current model fields in preparation for meeting
* [x] LESS from PF+A / GTA
* [x] Content Blocks
    * [x] Create Carousel Content Block
* [ ] Silvie to source and provide **4** Carousel Slide images
* [x] Confirm default fields for Carousel Slide model
* [x] Add migration to seed  4 Carousel Slide models with faker data and 1 Carousel Slide model with faker date and corresponding Vimeo video
* [ ] Replace migration seed faker images with those provided by Silvie
* [x] Add migration with user permissions
* [x] Controller Amendments
* [x] Model Amendments
* [x] Language References

**Fields**

`PFA\Gallery\Models\Slide`

* `is_public`
* `is_video`
* `name`
* `slug`
* `slide_image`
* `vimeo_id`

---

**Contact Plugin**

* https://github.com/thepottingshed/octobercms-form-builder-plugin

`ThePottingShed.FormBuilder`

* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-form-builder-plugin/issues/15 )
* [x] LESS from Mitchell / design based on Rok / Carey ( with Team removed ) / Mitchell
* [x] Confirm default fields for contact form
* [x] Add default form to seed

---

**Content Blocks Plugin**

* https://github.com/thepottingshed/octobercms-content-blocks-plugin

`ThePottingShed.ContentBlocks`

* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-content-blocks-plugin/issues/40 )
* [ ] Max width for single column text
* [ ] Submit issue to OctoberCMS repo demonstrating CMS Page form field validation error

---

**Portfolio Plugin**

* https://github.com/thepottingshed/octobercms-portfolio-plugin

`ThePottingShed.Portfolio`

* [x] Create Plugin Repo
* [x] Add Plugin Repo to Milestones
* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-portfolio-plugin/issues/1 )
* [x] Add default Labels with Jules script
* [x] List current model fields in preparation for meeting
* [x] LESS from Mitchell / design from Mitchell / Rok
* [x] Content Blocks
    * [x] Create Featured Projects Content Block
* [ ] Silvie to source and provide **9 * 10** Portfolio Project images
* [x] Confirm default fields for Portfolio Project model
* [x] Add migration to seed 9 Portfolio Project models with faker data
* [ ] Replace migration seed faker images with those provided by Silvie for the other plugins
* [x] Add migration to seed `RainLab.Sitemap`
* [x] Add migration to seed user permissions

**Fields**

`Mitchell\Projects\Model\Project`

* `is_public`
* `is_video`
* `is_hero`
* `title`
* `slug`
* `description`
* `hero_image`
* `gallery` <-- Actually images field 
* `video_url`

---

**Services Plugin**

* https://github.com/thepottingshed/octobercms-services-plugin

`ThePottingShed.Services`

* [x] Create Plugin Repo
* [x] Add Plugin Repo to Milestones
* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-services-plugin/issues/1 )
* [x] Add default Labels with Jules script
* [x] List current model fields in preparation for meeting
* [x] LESS from GTA Learning Solutions
* [ ] Silvie to source and provide **9** Service model images
* [x] Confirm default fields for Service model
* [x] Add migration to seed 9 Service models with faker data
* [ ] Replace migration seed faker images with those provided by Silvie
* [x] Add migration to seed `RainLab.Sitemap`
* [x] Add migration to seed user permissions

**Fields**

`GTA\LearningSolutions\Models\Solution`

* `title`
* `slug`
* `overview`
* `image`
* `copy`
* `is_featured`
* `is_public`

---

**Team Plugin**

* https://github.com/thepottingshed/octobercms-team-plugin

`ThePottingShed.Team`

* [x] Add Plugin Repo to Milestones
* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-team-plugin/issues/4 ) 
* [x] Add default Labels with Jules script
* [x] List current model fields in preparation for meeting
* [x] LESS from GTA
* [x] Content Blocks
    * [x] Create Key Contacts Content Block
* [ ] Silvie to source and provide **5** Team Member images
* [x] Create many to many relationship between department and member
* [x] Confirm default fields for Team Department model
* [x] Confirm default fields for Team Member model
* [x] Add migration to seed Team Department model with faker data
* [x] Add migration to seed 5 Team Member models with faker data
* [x] Add migration to seed Team Settings model with faker data
* [ ] Replace migration seed faker images with those provided by Silvie
* [x] Add migration to seed `RainLab.Sitemap`
* [x] Add migration to seed user permissions

**Fields**

`ThePottingShed\Team\Models\Department`

* `name`
* `slug`
* `colour`
* `is_public`

`ThePottingShed\Team\Models\Member`

* `name`
* `slug`
* `is_public`
* `is_key_contact`
* `email_address`
* `job_title`
* `telephone_number`
* `mobile_number`
* `linkedin_url`
* `post_nominals`
* `department` <-- Do we support `manyToMany` or `oneToMany` here?
* `biography`
* `profile_image`

---

**Testimonials Plugin**

* https://github.com/thepottingshed/octobercms-testimonials-plugin

`ThePottingShed.Testimonials`

* [x] Add Plugin Repo to Milestones
* [x] Create the below as issues in Plugin Repo ( https://github.com/thepottingshed/octobercms-testimonials-plugin/issues/3 )
* [x] Add default Labels with Jules script
* [x] List current model fields in preparation for meeting
* [x] LESS from Carey / Mitchell
* [x] Content Blocks
    * [x] Create Testimonial List Content Block
* [x] Confirm default fields for Testimonials Testimony model
* [x] Add migration to seed Testimonial Testimony model faker data
* [x] Add migration to seed user permissions

**Fields**

`ThePottingShed\Tesimonials\Models\Testimonial`

* `company`
* `slug`
* `is_public`
* `testimonial`

**Comment by seanthepottingshed** [comment]
@joshgosselin 

Velly intelesting Mista Bond

**Comment by seanthepottingshed** [comment]
@joshgosselin 

Can you upload your photos of meeting scribbles here please?

**Comment by joshgosselin** [comment]
![image from ios 1](https://user-images.githubusercontent.com/15610536/49019663-5643dd80-f186-11e8-90d7-e39195be84fb.jpg)
![image from ios](https://user-images.githubusercontent.com/15610536/49019664-57750a80-f186-11e8-9a7e-d6e2e916bdb0.jpg)
![image from ios 2](https://user-images.githubusercontent.com/15610536/49019676-6360cc80-f186-11e8-899e-f9806acce5da.jpg)

**Comment by seanthepottingshed** [comment]
@joshgosselin 

Cheers, I will break this into task below

**Comment by seanthepottingshed** [comment]
Plugins
---

* AddThis
* Backend
* Backup Manager
* Blog
* BugSnag
* Campaign Monitor
* Extra Form Widgets
* Form Builder
* GoogleAnalytics
* Outdated Browser
* pJax
* Privacy Policy
* Redirect
* SEO ( Meta, OpenGraph, TwitterCard, Schema, AMP )
* Sitemap
* SVG Sprites
* Theme
* Theme Colours
* TWIG
* UIKIt
* Web Fonts 

---

**AddThis Plugin**

`ThePottingShed.AddThis`

_Good to go_

---

**Backend Plugin**

`ThePottingShed.Backend`

_Good to go_

---

**Backup Manager Plugin**

`Renatio.BackupManager`

_Third Party plugin, good to go_

---

**Bug Snag Plugin**

`ThePottingShed.BugSnag`

_Good to go_

---

**Campaign Monitor Plugin**

`ThePottingShed.CampaignMonitor`

* [ ] Newsletter Sign Up Content Block

---

**Extra Form Widgets Plugin**

`ThePottingShed.ExtraFormWidgets`

_Good to go_

---

**Form Building Plugin**

`Renatio.FormBuilder`

_Good to go_

---

**Google Analytics Plugin**

`RainLab.GoogleAnalytics`
`ThePottingShed.GoogleAnalytics`

_Good to go_

---

**Outdated Browser Plugin**

`ThePottingShed.OutdatedBrowser`

* [ ] Add IE 10 and IE 11 to browser list

---

**Pjax Plugin**

`ThePottingShed.Pjax`

_Good to go_

---

**Privacy Policy Plugin**

`ThePottingShed.PrivacyPolicy`

_Good to go_

---

**Redirect Plugin**

`Vlpd.Redirect`

_Third party, good to go_

---

**SEO Plugins**

`ThePottingShed.Amp`
`ThePottingShed.Meta`
`ThePottingShed.OpenGraph`
`ThePottingShed.Schema`
`ThePottingShed.Seo`
`ThePottingShed.TwitterCard`

* [ ] Remove AMP CSS field

---

**SVG Sprites Plugin**

`ThePottingShed.SvgSprites`

_Good to go_

---

**Sitemap Plugin**

`RainLab.Sitemap`

_Third party, good to go_

---

**Theme  Plugin**

`ThePottingShed.Theme`

* [ ] Add field for SVG logo
* [ ] Contact form etc ( @davethepottingshed can you elaborate on this please )

---

**Theme Colours**

`ThePottingShed.ThemeColors`

_Good to go_

---

**TWIG Plugin**

`ThePottingShed.Twig`

_Good to go_

---

**UI KIt Plugin**

`ThePottingShed.UiKit`

_Good to go_

---

**Web Fonts Plugin**

`ThePottingShed.WebFonts`

_Good to go_

**Comment by seanthepottingshed** [comment]
@joshgosselin 

Still updating, can we schedule a meeting in today to go through and agree all the fields for each of the frontend plugins please?

**Comment by joshgosselin** [comment]
Yep 11am

You gonna list them out and we can just do a once over

**Comment by seanthepottingshed** [comment]
@joshgosselin 

Yeah will do that, once I've brain dumped and created all issues required for plugins, I will see what fields are in plugins that are already built

**Comment by joshgosselin** [comment]
🤙

**Comment by seanthepottingshed** [comment]
TPS Base Theme
---

* [ ] Create Repo with Jules OctoberCMS Set Up Script with `staging`
* [ ] Install all Core Plugins
* [ ] Install all Frontend Plugins
* [ ] Scaffold out `templates` 
* [ ] Scaffold out `pages`
* [ ] Scaffold out `partials`
* [ ] Action Plugins Issues

**Comment by seanthepottingshed** [comment]
@joshgosselin @davethepottingshed 

Just a thought - should we have some default favicons as part of the theme?

**Comment by joshgosselin** [comment]
Not sure what default would make sense… 

Can this be a theme field?

**Comment by seanthepottingshed** [comment]
@joshgosselin @davethepottingshed 

From today's meeting ( 12/12/18 ):

* [ ] Add Static Pages to Example user permissions
* [ ] Add default Privacy Policy and Cookie Policy
* [ ] List of default SEO data:
   * Home
   * Portfolio
   * Services
   * About
   * Team
   * Careers
   * News
   * Contact

@joshgosselin - would be good to just have some default SEO data which I can then pre-populate using website name as part of the automated plugin installation process

**Comment by joshgosselin** [comment]
Yep definitely worth just having default SEO data

**Comment by seanthepottingshed** [comment]
I was trying to find what Mr Platts provided us but PD site has changed since then

**Comment by seanthepottingshed** [comment]
@joshgosselin 

Release site set up:

* https://tps-base-theme.tps.digital

**Comment by seanthepottingshed** [comment]
@joshgosselin 

Just need SEO example SEO data for each page and just about done then methinks
